apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vks-demo
  namespace: argocd
spec:
  description: VKS Secret Store demonstration workloads
  sourceRepos:
    - https://github.com/volraton/vks-secret-store-demo.git
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
    - namespace: demo-platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
